changelog:
  exclude:
    labels:
      - skip-changelog
      - duplicate
      - invalid
      - question
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - feat
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: Maintenance
      labels:
        - chore
        - ci
        - dependencies
    - title: Other Changes
      labels:
        - "*"
